source.. = src/,\
           resources/,\
           languages/,\
           test/
output.. = bin/
bin.includes = plugin.xml,\
               META-INF/,\
               .,\
               icons/,\
               lib/bined-core-0.3.0-SNAPSHOT.jar,\
               lib/bined-highlight-swing-0.3.0-SNAPSHOT.jar,\
               lib/bined-section-0.3.0-SNAPSHOT.jar,\
               lib/bined-operation-0.3.0-SNAPSHOT.jar,\
               lib/bined-operation-swing-0.3.0-SNAPSHOT.jar,\
               lib/bined-swing-0.3.0-SNAPSHOT.jar,\
               lib/bined-swing-section-0.3.0-SNAPSHOT.jar,\
               lib/binary_data-0.3.0-SNAPSHOT.jar,\
               lib/binary_data-array-0.3.0-SNAPSHOT.jar,\
               lib/binary_data-delta-0.3.0-SNAPSHOT.jar,\
               lib/bcprov-jdk18on-1.80.jar,\
               lib/bined-jaguif-bookmarks-0.3.0-SNAPSHOT.jar,\
               lib/bined-jaguif-compare-0.3.0-SNAPSHOT.jar,\
               lib/bined-jaguif-component-0.3.0-SNAPSHOT.jar,\
               lib/bined-jaguif-document-0.3.0-SNAPSHOT.jar,\
               lib/bined-jaguif-editor-0.3.0-SNAPSHOT.jar,\
               lib/bined-jaguif-inspector-0.3.0-SNAPSHOT.jar,\
               lib/bined-jaguif-legacy-0.3.0-SNAPSHOT.jar,\
               lib/bined-jaguif-macro-0.3.0-SNAPSHOT.jar,\
               lib/bined-jaguif-objectdata-0.3.0-SNAPSHOT.jar,\
               lib/bined-jaguif-operation-bouncycastle-0.3.0-SNAPSHOT.jar,\
               lib/bined-jaguif-operation-code-0.3.0-SNAPSHOT.jar,\
               lib/bined-jaguif-operation-method-0.3.0-SNAPSHOT.jar,\
               lib/bined-jaguif-search-0.3.0-SNAPSHOT.jar,\
               lib/bined-jaguif-theme-0.3.0-SNAPSHOT.jar,\
               lib/bined-jaguif-tool-content-0.3.0-SNAPSHOT.jar,\
               lib/bined-jaguif-viewer-0.3.0-SNAPSHOT.jar,\
               lib/component-dropdownbutton-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-action-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-action-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-action-manager-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-basic-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-component-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-component-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-context-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-context-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-contribution-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-contribution-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-core-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-docking-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-docking-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-docking-multi-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-docking-multi-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-document-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-document-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-document-recent-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-file-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-file-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-frame-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-frame-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-help-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-help-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-help-online-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-help-online-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-language-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-language-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-license-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-license-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-menu-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-menu-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-menu-popup-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-menu-popup-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-operation-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-operation-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-operation-undo-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-operation-undo-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-options-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-options-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-options-settings-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-options-settings-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-search-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-search-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-sidebar-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-sidebar-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-statusbar-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-statusbar-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-tabpages-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-tabpages-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-text-encoding-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-text-font-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-toolbar-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-toolbar-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-ui-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-ui-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-ui-theme-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-ui-theme-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-utils-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-window-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-window-api-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-iconset-material-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-language-ja_JP-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-language-ko_KR-0.3.0-SNAPSHOT.jar,\
               lib/jaguif-language-zh_Hans-0.3.0-SNAPSHOT.jar,\
               lib/jspecify-1.0.0.jar,\
               lib/jsr305-2.0.1.jar
